# Generated by Django 4.2.7 on 2025-11-14 20:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('total_records', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CSV Upload',
                'verbose_name_plural': 'CSV Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_equipment', models.IntegerField(default=0)),
                ('active_equipment', models.IntegerField(default=0)),
                ('inactive_equipment', models.IntegerField(default=0)),
                ('maintenance_equipment', models.IntegerField(default=0)),
                ('type_distribution', models.JSONField(default=dict)),
                ('avg_flowrate', models.FloatField(blank=True, null=True)),
                ('max_flowrate', models.FloatField(blank=True, null=True)),
                ('min_flowrate', models.FloatField(blank=True, null=True)),
                ('avg_pressure', models.FloatField(blank=True, null=True)),
                ('avg_temperature', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('csv_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='api.csvupload')),
            ],
            options={
                'verbose_name': 'Data Summary',
                'verbose_name_plural': 'Data Summaries',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=100, unique=True)),
                ('equipment_name', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(choices=[('Pump', 'Pump'), ('Valve', 'Valve'), ('Tank', 'Tank'), ('Reactor', 'Reactor'), ('Heat Exchanger', 'Heat Exchanger'), ('Compressor', 'Compressor'), ('Separator', 'Separator'), ('Mixer', 'Mixer'), ('Filter', 'Filter'), ('Other', 'Other')], max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.FloatField(blank=True, help_text='Capacity in appropriate units', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('flowrate', models.FloatField(blank=True, help_text='Flow rate in L/min or appropriate units', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pressure', models.FloatField(blank=True, help_text='Operating pressure in bar or psi', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('temperature', models.FloatField(blank=True, help_text='Operating temperature in °C', null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Maintenance'), ('Decommissioned', 'Decommissioned')], default='Active', max_length=20)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('csv_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='api.csvupload')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['equipment_id'],
                'indexes': [models.Index(fields=['equipment_id'], name='api_equipme_equipme_739915_idx'), models.Index(fields=['equipment_type'], name='api_equipme_equipme_985097_idx'), models.Index(fields=['status'], name='api_equipme_status_26dd77_idx')],
            },
        ),
    ]
