# Generated by Django 4.2.7 on 2025-11-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='additional_params',
            field=models.JSONField(blank=True, default=dict, help_text='Store additional dynamic parameters from CSV (e.g., humidity, vibration, etc.)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('Pump', 'Pump'), ('Valve', 'Valve'), ('Tank', 'Tank'), ('Reactor', 'Reactor'), ('Heat Exchanger', 'Heat Exchanger'), ('Compressor', 'Compressor'), ('Separator', 'Separator'), ('Mixer', 'Mixer'), ('Filter', 'Filter'), ('HeatExchanger', 'HeatExchanger'), ('Condenser', 'Condenser'), ('Other', 'Other')], max_length=50),
        ),
    ]
